source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

workspace 'ExampleObviousApp'

target 'ExampleObviousApp' do
  use_frameworks!

  # Pods for ObviousDemoAPI
  pod 'ObviousAPI'

  project 'ExampleObviousApp/ExampleObviousApp.xcodeproj'

  target 'ExampleObviousAppTests' do
    inherit! :search_paths
    # Pods for testing
  end
 
end
